### ISSUE TITLE
kcptun无法自启动

### ISSUE THREAD

**Issue by baggiogogo** [kuoruan/luci-app-kcptun#1]
功能使用一切正常，就是无法自启动，每次要去启动项点下开始，或者kcptun服务里边点下保存应用。
还有就是系统进程里边找不到kcptun，不知这是不是问题。

**Comment by kuoruan** [comment]
这个问题我发现了，正在处理...
第一次完整写一个luci，还没什么经验

**Comment by baggiogogo** [comment]
木事，慢慢来，有这个已经方便很多了，感谢感谢。
另外如有需要可以看看这个项目https://github.com/EasyPi/openwrt-kcptun，我也试验了，可以自启动。同样openwrt网页查看系统进程也找不到，看来这个不是什么问题。

**Comment by kuoruan** [comment]
@baggiogogo  https://github.com/kuoruan/luci-app-kcptun/commit/ead461548e63d5f15df3d17a9dab91ab28e6196b 已修复

**Comment by baggiogogo** [comment]
非常感谢，下载了最新版，目前一切正常。
