### ISSUE TITLE
LuCI中填入IPv6地址后保存不能生成正确的config文件

### ISSUE THREAD

**Issue by libc0607** [kuoruan/luci-app-kcptun#11]
你好，我在使用的固件里集成了luci-app-kcptun的1.1.3版本
网络环境为教育网原生IPv6
在LuCI的服务器地址中填入IPv6地址后保存，kcptun不能启动，日志报too many colons in address ..这种错误
换IPv4地址其他配置相同就正常使用
然后发现是因为自动生成的/var/etc/kcptun/client.json这个文件中的IPv6地址没有自动加[]，将init.d中的write_client_config()函数相关部分改动了一下，渣Shell水平求不喷，应该有写得更好的方法

`server_ipv6_flag=`echo $server |awk '/:/'`
    if [ "$server_ipv6_flag" = "" ]; then
        printf ',\n  "remoteaddr": "%s:%s"' "$server" "$server_port" >>$CLIENT_CONFIG
    else
        printf ',\n  "remoteaddr": "%s:%s"' "[$server]" "$server_port" >>$CLIENT_CONFIG        
    fi
`
改后填入IPv4和IPv6均可正常使用

**Comment by kuoruan** [comment]
等下个版本我加个选项吧

**Comment by libc0607** [comment]
好的，多谢

**Comment by kuoruan** [comment]
已实现，等待发版
https://github.com/kuoruan/luci-app-kcptun/commit/b94f260cf4e9a897211971df27e621ed4a4f296d
