### ISSUE TITLE
client 端 localaddr 键值。

### ISSUE THREAD

**Issue by dansean** [kuoruan/luci-app-kcptun#12]
如果可以的话，能添加 localaddr 选项吗？或者默认 127.0.0.1 .每次跟新后还要手动改有点麻烦呢……

**Comment by kuoruan** [comment]
你的意思是你的监听IP不是 127.0.0.1 吗？

**Comment by dansean** [comment]
@kuoruan 
比如昨天更新的在我这生成的json，监听地址默认大概是这样的：localaddr：[::]:8888
然后我lsof了以下没看到这个端口.

**Comment by dansean** [comment]
@kuoruan 
重装了一下
启动文件：
printf '\n  "localaddr": ":%s"' "$local_port" >>$CLIENT_CONFIG

现实中：
listening on: [::]:12948

**Comment by kuoruan** [comment]
https://github.com/kuoruan/luci-app-kcptun/commit/29ed46537c4353aad6c1c39bfc5d37be0831e407

已实现
