### ISSUE TITLE
WNDR4300 安装luci-app-kcptun_1.2.1-1_chaos-calmer_all.ipk后出错

### ISSUE THREAD

**Issue by zhgcao** [kuoruan/luci-app-kcptun#14]
刷的openwrt 15.05.01，不管是chaos-calmer，还是designated-driver版，均出错

错误信息：
/usr/lib/lua/luci/controller/kcptun.lua:52: attempt to call global 'post' (a nil value)
stack traceback:
	/usr/lib/lua/luci/controller/kcptun.lua:52: in function 'v'
	/usr/lib/lua/luci/dispatcher.lua:536: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:201: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:168: in function </usr/lib/lua/luci/dispatcher.lua:167>

**Comment by kuoruan** [comment]
先卸载再装 chaos-calmer， 文件没问题

**Comment by zhgcao** [comment]
卸载重装了好几次了，都不行，不知道为啥

**Comment by kuoruan** [comment]
看看 /usr/lib/lua/luci/controller/kcptun.lua 这个文件

**Comment by kuoruan** [comment]
你手动改吧：
https://github.com/kuoruan/luci-app-kcptun/commit/e93390af298c4a4b71868d4943cdd6198ed45370

**Comment by 1001knight** [comment]
opkg install luci-app-kcptun_1.2.0-1_chaos-calmer_all.ipk
opkg install luci-i18n-kcptun-zh-cn_1.2.0-1_all.ipk
按顺序安装，wnrt4300，openwrt 15.05.01，已成功，正在测试，发现没pc端快，YouTube峰值7m/s。电脑端是13m/s。
