### ISSUE TITLE
shadowsocks无法通过与1.2.1-1_chaos-calmer_all版本连接

### ISSUE THREAD

**Issue by 3xpert** [kuoruan/luci-app-kcptun#15]
路由是NetGear R6100，固件是chaos-calmer。
之前可通过：
1.Shadowsocks-windows + luci-app-kcptun_1.1.3-1_chaos-calmer_all + @bettermanbao's kcptun-openwrt-ar71xx-20160912进行上网加速。
现在的：
2.Shadowoscks-windows + luci-app-kcptun_1.2.1-1_chaos-calmer_all + @bettermanbao's kcptun-openwrt-ar71xx-20161118 不能上网，Shadowsocks-windows日志显示“目标主机积极拒绝”
以上硬件环境、参数设置是一样的。

**Comment by kuoruan** [comment]
windows 上 telnet 路由器ip kcptun 端口 通不通？

**Comment by 3xpert** [comment]
上述的1，在telnet后没返回任何结果。2，返回连接失败
路由器刷完openwrt不就不能telnet了吗？

**Comment by kuoruan** [comment]
把路由器的防火墙关了，或者手动放行 kcptun 端口

**Comment by 3xpert** [comment]
好的，谢谢！

**Comment by 3xpert** [comment]
关了防火墙，2还是不行

**Comment by kuoruan** [comment]
开日志，看看有日志输出没有

**Comment by 3xpert** [comment]
有输出kcptun启动时读取参数那部份，运行过程的日志好像都没见到过。1、2都一样。

**Comment by kuoruan** [comment]
路由器上用 netstat 能看到 kcptun 端口吗？

**Comment by 3xpert** [comment]
这要晚上回家再测试。

**Comment by 3xpert** [comment]
netstat后1有看到kcptun的端口，2没有

**Comment by kuoruan** [comment]
那就是 kcptun 没启动起来， ps -w 看看有没有 kcptun 进程

**Comment by 3xpert** [comment]
当然有

**Comment by kuoruan** [comment]
有进程没端口？这怎么可能

**Comment by kuoruan** [comment]
有进程没端口？这怎么可能

**Comment by 3xpert** [comment]
PID  PPID USER     STAT   VSZ %VSZ %CPU COMMAND
11222     1 root     S     3400   3%   9% ss-local -c /var/etc/shadowsocks.json
11288     1 root     R     1660   1%   1% /usr/sbin/hostapd -P /var/run/wifi-ph
12405 11446 root     R     1364   1%   0% top
    3     2 root     SW       0   0%   0% [ksoftirqd/0]
11655     1 root     R     773m 629%   0% /usr/bin/kcptun/client -c /var/etc/kc
11445   956 root     S     1244   1%   0% /usr/sbin/dropbear -F -P /var/run/dro
11000     1 root     S     3588   3%   0

**Comment by 3xpert** [comment]
root@OpenWrt:~# ps -w | grep kcptun
11655 root      773m S    /usr/bin/kcptun/client -c /var/etc/kcptun/client.json

**Comment by kuoruan** [comment]
看看 /var/etc/kcptun/client.json 这个文件里边配置的端口是哪个，然后 netstat -npl | grep 端口

**Comment by 3xpert** [comment]
root@OpenWrt:~# netstat -npl | grep 8388
tcp        0      0 127.0.0.1:8388          0.0.0.0:*               LISTEN      11655/client

**Comment by kuoruan** [comment]
这不是有端口吗，将 client 的本地监听地址改为 0.0.0.0 试试

**Comment by 3xpert** [comment]
但是netstat列印出来的结果的确没有这个端口呢

**Comment by 3xpert** [comment]
本地地址改成0.0.0.0，可以了。这是什么原因呢？

**Comment by kuoruan** [comment]
监听 127.0.0.1 会只允许本机连接
