### ISSUE TITLE
结贴，路由版本的问题，跟kcptun没有关系

### ISSUE THREAD

**Issue by kukudemajia** [kuoruan/luci-app-kcptun#16]
LEDE下无法安装
Collected errors:
 * wfopen: //usr/lib/opkg/info/luci-app-kcptun.control: Read-only file system.
 * wfopen: //usr/lib/opkg/info/luci-app-kcptun.postinst: Read-only file system.
 * wfopen: //usr/lib/opkg/info/luci-app-kcptun.postinst-pkg: Read-only file system.
 * wfopen: //usr/lib/opkg/info/luci-app-kcptun.prerm: Read-only file system.
 * wfopen: /etc/config/kcptun: Read-only file system.
 * wfopen: /etc/init.d/kcptun: Read-only file system.
 * wfopen: /etc/uci-defaults/40_luci-kcptun: Read-only file system.
 * wfopen: /usr/bin/kcptun_monitor: Read-only file system.
 * wfopen: /usr/lib/lua/luci/controller/kcptun.lua: Read-only file system.
 * wfopen: /usr/lib/lua/luci/model/cbi/kcptun/client.lua: Read-only file system.
 * wfopen: /usr/lib/lua/luci/model/cbi/kcptun/list.lua: Read-only file system.
 * wfopen: /usr/lib/lua/luci/model/cbi/kcptun/overview.lua: Read-only file system.
 * wfopen: /usr/lib/lua/luci/model/cbi/kcptun/server.lua: Read-only file system.
 * wfopen: /usr/lib/lua/luci/model/cbi/kcptun/settings.lua: Read-only file system.
 * extract_archive: Cannot make dir /usr/lib/lua/luci/view/kcptun/: Read-only file system.
 * wfopen: /usr/lib/lua/luci/view/kcptun/overview.htm: No such file or directory.
 * pkg_write_filelist: Failed to open //usr/lib/opkg/info/luci-app-kcptun.list: Read-only file system.
 * opkg_install_pkg: Failed to extract data files for luci-app-kcptun. Package debris may remain!
 * opkg_install_cmd: Cannot install package luci-app-kcptun.

**Comment by kuoruan** [comment]
LEDE 上直接安装就能使用，你的问题看看是不是路由器空间不足了。

**Comment by kukudemajia** [comment]
Esxi跑的虚拟机，lede-17.01.0-rc2-r3131-42f3c1f-x86-64-combined-ext4.img这个版本

**Comment by kuoruan** [comment]
你装装其他软件，估计也装不上

**Comment by kukudemajia** [comment]
呃，中文包都可以安装，还真的是其它包就装不上，我换个版本试试看，不好意思

**Comment by kukudemajia** [comment]
结贴，路由版本的问题，跟kcptun没有关系
