### ISSUE TITLE
kcp-monitor与LEDE luCI存在兼容问题

### ISSUE THREAD

**Issue by PutinYpa** [kuoruan/luci-app-kcptun#17]
LEDE uci 不能正确处理 -q参数，需要把错误输出重定向到 /dev/null
例如：uci get -q kcptun.@general[0].enable_server
改为：uci get kcptun.@general[0].enable_server 2>/dev/null

**Comment by kuoruan** [comment]
不清楚你是用的哪个版本，我这里能正常使用 -q
