### ISSUE TITLE
make menuconfig的时候在LuCI里找不到luci-app-kcptun选项

### ISSUE THREAD

**Issue by ghost** [kuoruan/luci-app-kcptun#18]
在ledeV17.01源码编译，make menuconfig的时候在LuCI里找不到luci-app-kcptun选项。

**Comment by kuoruan** [comment]
你是按照我的编译说明的步骤做的吗？

**Comment by ghost** [comment]
是的，同时编译的软件还有其它十几个软件。

**Comment by kuoruan** [comment]
那你就只有找找你自己环境的问题了，通常删掉 tmp 文件夹就没问题的

**Comment by ghost** [comment]
其它十几个软件都能正常选择和编译

**Comment by kuoruan** [comment]
feeds/luci/applications/ 下面能看到包吗？

**Comment by ghost** [comment]
可以

**Comment by ghost** [comment]
源码也是全新下载的lede并git checkout到V17.01的

**Comment by kuoruan** [comment]
```
rm -rf tmp/

./scripts/feeds update -a
./scripts/feeds install -a
```

我一直是用 lede 的 master 分支编译的，源码不会有问题

**Comment by ghost** [comment]
我再试试，谢谢大神热心解答！

**Comment by ghost** [comment]
刚才又试了一遍，还是不行。并提示错误如下：
ERROR: please fix feeds/yuan/luci/applications/luci-app-kcptun/Makefile - see logs/feeds/yuan/luci/applications/luci-app-kcptun/dump.txt for details
Collecting package info: done

不知是否和我直接把软件源码下载到本地作为feeds源有关？

**Comment by kuoruan** [comment]
亲，你放的目录都错了，我再三确认了你的目录，结果还是错了

**Comment by ghost** [comment]
我是直接把软件源码下载到本地作为feeds源也就是把下载好的本地源添加到feeds.conf.default中，我一直以来都是这样做的，并且其它软件都能正常编译

**Comment by kuoruan** [comment]
你难道没看出来我的目录结构不一样么？我写的是原版的目录结构，需要放到原版目录下，不能通过第三方加载

**Comment by ghost** [comment]
~/lede/source$ ./scripts/feeds update -a
Updating feed 'yuan' from '/home/xsm/wrt1900acs/yuan/feeds' ...
Create index file './feeds/yuan.index' 
ERROR: please fix feeds/yuan/luci/applications/luci-app-kcptun/Makefile - see logs/feeds/yuan/luci/applications/luci-app-kcptun/dump.txt for details
Collecting package info: done
Updating feed 'package' from '/home/xsm/wrt1900acs/yuan/package' ...
Create index file './feeds/package.index' 
Collecting package info: done

**Comment by kuoruan** [comment]
请按编译说明做：
https://github.com/kuoruan/luci-app-kcptun#编译说明
此 Issue 关闭了。

**Comment by ghost** [comment]
所有的lede软件都是通过根目录中的feeds.conf.default下载的啊，我只是把我要的软件源码加入。

**Comment by kuoruan** [comment]
你就放到 lede 本来的 luci 目录下就行了，放其他任何位置都加载不上。

**Comment by ghost** [comment]
再次谢谢大神解答，同时也期待以后的版本可以兼容feeds.conf.default加载。

**Comment by kuoruan** [comment]
以后也不会兼容的，写成那种没有任何意义
