### ISSUE TITLE
OpenWRT 上无法启动 kcptun

### ISSUE THREAD

**Issue by KittenYang** [kuoruan/luci-app-kcptun#19]
我按照[这篇教程](https://zhongyue.site/openwrt_kcptun/)一切都配置好了，然而按下【保存&应用】之后就被打回原形了。
<img width="1042" alt="2017-03-07 23 31 39" src="https://cloud.githubusercontent.com/assets/5517281/23663776/97c4e034-038e-11e7-9cfe-cb375aab5143.png">
<img width="1035" alt="2017-03-07 23 31 48" src="https://cloud.githubusercontent.com/assets/5517281/23663779/990bf59a-038e-11e7-8999-eaf22251d30c.png">

是因为我的路由器配置不够导致  kcp 服务一起直接被 kill 掉了吗？

**Comment by kuoruan** [comment]
你路由器是 MT7620 的吗？可以试试把服务端的压缩和加密关掉

**Comment by KittenYang** [comment]
@kuoruan  路由器网件3800，刷的是明月永在去年的 openwrt，服务端的压缩和加密关掉了，还在不行。

**Comment by kuoruan** [comment]
你把日志打开 Enable Logging，看看日志的输出

**Comment by KittenYang** [comment]
@kuoruan 好，晚上回家试试
