### ISSUE TITLE
手动模式似乎失效

### ISSUE THREAD

**Issue by baggiogogo** [kuoruan/luci-app-kcptun#2]
2016/09/29 21:00:07 nodelay parameters: 0 40 2 0
手动模式，除了40对应的interval项以及2对应的resend项填入数值会产生变动，其余nodelay以及nc项无论怎么勾选，启动后日志均输出0，也不知是否正确启动，如果直接手动改动/etc/config/kcptun配置文件，启动后日志则可以正确显示如1 40 2 1，不知是否是bug。

**Comment by kuoruan** [comment]
OK, 我检查一下
