### ISSUE TITLE
路由器上设置完kcptun后，ss是不是要改设置？

### ISSUE THREAD

**Issue by SteedJoy** [kuoruan/luci-app-kcptun#20]
路由器上的ss是不是也要改成127.0.0.1和kcptun的当前端口才能启用呢？

**Comment by kuoruan** [comment]
对

**Comment by SteedJoy** [comment]
设置和配置列表里都设好了，然而总览里的运行状态却一直显示“客户端状态：未运行”。如何才能启用客户端呀？

**Comment by kuoruan** [comment]
你把日志打开，看看有没有日志输出，一般这种都是被杀掉了

**Comment by SteedJoy** [comment]
没有日志输出……  呃，是被什么进程杀掉了，怎么搞定呢？

**Comment by kuoruan** [comment]
你确定你配置好了的？上截图

**Comment by SteedJoy** [comment]
![qq 20170318180123](https://cloud.githubusercontent.com/assets/12250878/24071102/8ca74dde-0c05-11e7-94db-2e21d6d06779.jpg)
![qq 20170318180202](https://cloud.githubusercontent.com/assets/12250878/24071103/90a092e2-0c05-11e7-8893-c2173eb3e167.jpg)

**Comment by kuoruan** [comment]
我的意思是把日志记录打开。。。你这不是没开么

**Comment by SteedJoy** [comment]
之前打开了，一直未运行，刚才重新设置了一遍，就关掉了。
![qq 20170318180935](https://cloud.githubusercontent.com/assets/12250878/24071132/20933f44-0c06-11e7-9c32-672d4addf5ae.jpg)
![qq 20170318180949](https://cloud.githubusercontent.com/assets/12250878/24071133/220cfb26-0c06-11e7-8901-c87e1ba5f3e8.jpg)

现在又打开了，还是这样，未运行，日志文件不存在。

**Comment by kuoruan** [comment]
下面的进程监控日志呢？

**Comment by kuoruan** [comment]
你进去 /var/etc/kcptun 看看里边有没有 client.json 文件

**Comment by SteedJoy** [comment]
监控日志也是空的。 /var/etc下竟然没有kcptun的目录……

**Comment by kuoruan** [comment]
路由器满了吧，你 df -h 看看

**Comment by SteedJoy** [comment]
![image](https://cloud.githubusercontent.com/assets/12250878/24071258/9c6ef3f4-0c08-11e7-90dc-8bb61c084746.png)

**Comment by kuoruan** [comment]
1.手动运行 /etc/init.d/kcptun start 看看能不能启动
2.直接找到你的 kcptun 客户端文件，运行，看能不能启动。

**Comment by SteedJoy** [comment]
手动运行 /etc/init.d/kcptun start，启动了！

日志也有了！
![image](https://cloud.githubusercontent.com/assets/12250878/24071294/9cc5e42e-0c09-11e7-9646-028d7c6e16b1.png)

**Comment by SteedJoy** [comment]
然而，ss改到127.0.0.1:9527之后，外网打不开了……

**Comment by kuoruan** [comment]
ss 的问题我不处理，只处理 luci kcptun 方面的问题

**Comment by SteedJoy** [comment]
收到，多谢！：）
