### ISSUE TITLE
LEDE上无法启动

### ISSUE THREAD

**Issue by tporwx** [kuoruan/luci-app-kcptun#22]
LEDE上client始终无法启动，server倒是可以启动。
路由是WNDR4300。

**Comment by kuoruan** [comment]
开启日志，看看日志有没有输出

**Comment by tporwx** [comment]
根本没有启动过，也就没有日志生成啊。

**Comment by kuoruan** [comment]
手动启动试试 ```/etc/init.d/kcptun start```

**Comment by tporwx** [comment]
中午回去试试

**Comment by tporwx** [comment]
还是不行，启动不了。

**Comment by tporwx** [comment]
login as: root
root@192.168.1.1's password:


BusyBox v1.25.1 () built-in shell (ash)

     _________
    /        /\      _    ___ ___  ___
   /  LE    /  \    | |  | __|   \| __|
  /    DE  /    \   | |__| _|| |) | _|
 /________/  LE  \  |____|___|___/|___|                      lede-project.org
 \        \   DE /
  \    LE  \    /  -----------------------------------------------------------
   \  DE    \  /    Reboot (17.01.0, r3205-59508e3)
    \________\/    -----------------------------------------------------------

root@LEDE:~# /etc/init.d/kcptun start
Starting kcptun...
root@LEDE:~# /etc/init.d/kcptun start
Starting kcptun...
root@LEDE:~# /etc/init.d/kcptun start
Starting kcptun...
root@LEDE:~#

**Comment by kuoruan** [comment]
/var/etc/kcptun 里边有配置文件生成吗

**Comment by tporwx** [comment]
有的。

{
  "localaddr": "0.0.0.0:572",
  "remoteaddr": "xxxx:xxx",
  "key": "********",
  "crypt": "salsa20",
  "mode": "fast2",
  "conn": 1,
  "autoexpire": 60,
  "mtu": 512,
  "sndwnd": 256,
  "rcvwnd": 512,
  "datashard": 10,
  "parityshard": 3,
  "dscp": 46,
  "nocomp": true,
  "sockbuf": 4398046511104,
  "keepalive": 10,
  "log": "/var/log/kcptun/kcptun-client.log"
}

**Comment by tporwx** [comment]
路由器上的clinet是0221版本，VPS上的server是最新的0329版本的，不知是否有影响？

**Comment by kuoruan** [comment]
最好两端一致，不然可能会有问题

**Comment by tporwx** [comment]
直接打命令就能启动了，看来是luci对LEDE还是有兼容问题

**Comment by tporwx** [comment]
我自己用LEDE的SDK编译了一个也不行

**Comment by sotux** [comment]
我用 LEDE 源码编译，也启动不了，luci 版本 1.3.3-1，用 /etc/init.d/kcptun start 可以启动。

**Comment by kuoruan** [comment]
@sotux 有写机器上就是会出现这个问题，现在还在处理中。

**Comment by kuoruan** [comment]
@sotux 找到问题的原因了。你进 系统 -> 启动项 里边把 kcptun 禁用了。然后回去 luci 就行了

**Comment by sotux** [comment]
@kuoruan 安装好后，启动项里的 kcptun 是禁用状态，启用后就好了
