### ISSUE TITLE
一个或多个选项值有误

### ISSUE THREAD

**Issue by TuarusMars** [kuoruan/luci-app-kcptun#23]
点击保存&应用就会显示一个红框框住客户端可执行文件，出现 一个或多个选项值有误
![1](https://user-images.githubusercontent.com/25863624/27399994-4e7382da-56f1-11e7-86ae-ba777f18d54b.png)

**Comment by kuoruan** [comment]
说明这个文件不存在或者不是 kcptun 的文件
