### ISSUE TITLE
Configuration List

### ISSUE THREAD

**Issue by pingshu** [kuoruan/luci-app-kcptun#24]
/usr/lib/lua/luci/dispatcher.lua:460: Failed to execute cbi dispatcher target for entry '/admin/services/kcptun/list'.
The called action terminated with an exception:
/usr/lib/lua/luci/cbi.lua:53: Model 'kcptun/list' not found!
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:460: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:141: in function </usr/lib/lua/luci/dispatcher.lua:140>

**Comment by kuoruan** [comment]
你的旧版本没卸载吗？先卸载掉

**Comment by pingshu** [comment]
卸载了，我重启试试

**Comment by kuoruan** [comment]
rm -rf /tmp/luci-*

**Comment by pingshu** [comment]
卸载了，重启再安装以后就好了，谢谢
