### ISSUE TITLE
kcptun客户端显示“未运行”

### ISSUE THREAD

**Issue by ghost** [kuoruan/luci-app-kcptun#25]
刷了R7800的LEAN版本，内置1.3.3-2版本，在kcptun中服务器列表中添加了服务器，然后通过winscp将kcptun-linux-arm-20170525.tar中的client_linux_arm7改名为client并上传/usr/bin/kcptun（新建文件夹）目录中后，Kcptun - 常规设置不报错了，但是在客户端状态中显示“ 未运行”，请问该如何才能开启。我的操作是不是有错误。我将降级成1.3.3-1版本，通过opkg install安装，显示已安装1.3.3-2版本，不能降级，请问跟版本有关系没。

在设置中已”启用日记记录“，但是在“概况”一栏中均不显示“客户端日志”和“事件日志”，提醒“日记文件不存在”，所以我也不知道哪里出错l

**Comment by kuoruan** [comment]
你看看你的启动项里边，kcptun 服务是不是没启用。

**Comment by kuoruan** [comment]
另外，强制覆盖可以加 --force-reinstall 参数

**Comment by ghost** [comment]
查看了启动项，处于禁用，现已开启

2017年9月4日 +0800 09:59 Xingwang Liao <notifications@github.com>，写道：
