### ISSUE TITLE
可否针对kcpraw做一版

### ISSUE THREAD

**Issue by hhmob** [kuoruan/luci-app-kcptun#27]
一个不错的kcptun分支，伪装TCP连接，不容易被QoS，希望扩软兄弟能出一版针对这个的luci
https://github.com/ccsexyz/kcpraw

**Comment by kuoruan** [comment]
kcpraw 和 kcptun 的配置貌似差不多，做少量修改就行了，等我空了我会同时支持的

**Comment by hhmob** [comment]
太好了，多谢扩软兄！期待
