### ISSUE TITLE
MIPS FPU Emulator 

### ISSUE THREAD

**Issue by tporwx** [kuoruan/luci-app-kcptun#28]
最新的Golang 支持 soft float 了么？
LEDE还需要开启MIPS FPU Emulator么？

**Comment by kuoruan** [comment]
看这个 Issue: https://github.com/golang/go/issues/18162#issuecomment-307207805
大概 1.10 就会有了
而且从最后一个回复可以看出，代码 Review 已经过了，但是还没合并到 master（截至 7月 30号）

**Comment by tporwx** [comment]
希望能够尽快支持，这样就能直接用LEDE官方的固件了。
