### ISSUE TITLE
服务端可执行文件

### ISSUE THREAD

**Issue by 3xpert** [kuoruan/luci-app-kcptun#3]
这个文件哪里有？

**Comment by kuoruan** [comment]
你不启用服务端的话就不用管它，这个文件是用来在路由器上起 kcptun 服务端用的

**Comment by 3xpert** [comment]
但在保存應用的時候，總是提示出錯

Hsing-Wang Liao notifications@github.com于2016年10月9日 周日 17:00写道：

**Comment by kuoruan** [comment]
你把钩去掉不就得了

**Comment by 3xpert** [comment]
哦，謝謝！XD

于 2016年10月9日 GMT+08:0017:15:09, Hsing-Wang Liao notifications@github.com 写到:

> 你把钩去掉不就得了
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/kuoruan/luci-app-kcptun/issues/3#issuecomment-252474768

## 

b.rgd!
Tom
