### ISSUE TITLE
使用kcptun无法连接

### ISSUE THREAD

**Issue by wl56012102** [kuoruan/luci-app-kcptun#30]
vmware中运行lede，下载kcptun amd64的client 直接命令行里输入指令一切，ss连一切正常，使用web界面输入参数之后运行就无法链接网络，web管理界面在运行时加入了别的参数导致服务器不一致才不能使用还是什么原因

**Comment by kuoruan** [comment]
没有的，你可以把日志打开看看，生成的配置文件在 /var/etc/kcptun 目录下，你可以打开看看

**Comment by wl56012102** [comment]
我自己命令行运行的参数里没有nocamp,acknodelay这几个参数，然后他生成的配置里就有这几个参数
