### ISSUE TITLE
因openwrt base-luci 升级出现的页面错误

### ISSUE THREAD

**Issue by fuqiang03** [kuoruan/luci-app-kcptun#32]
![qq 20180407222952](https://user-images.githubusercontent.com/26851715/38456113-34d538d6-3ab3-11e8-8334-764c4d075013.png)

**Comment by kuoruan** [comment]
你这个看着不像我的原版，应该是被改过的

**Comment by fuqiang03** [comment]
亲 真的是原版哦 出现同一个错误的还有ngrok
![qq 20180408103141](https://user-images.githubusercontent.com/26851715/38462336-1249a760-3b18-11e8-816f-409467095201.png)

**Comment by kuoruan** [comment]
试试，看看是不是这里的问题

**Comment by fuqiang03** [comment]
老外升级了base-luci  连uci 都不能直接调用了 现在 lede luci 来个整个的大升级
