### ISSUE TITLE
打开服务端管理显示异常

### ISSUE THREAD

**Issue by wanacuiyu** [kuoruan/luci-app-kcptun#33]
500 内部服务器错误
对不起，服务器遇到未知错误。
/usr/lib/lua/luci/dispatcher.lua:407: Failed to execute arcombine dispatcher target for entry '/admin/services/kcptun/servers'.
The called action terminated with an exception:
/usr/lib/lua/luci/template.lua:55: Failed to execute template 'cbi/map'.
A runtime error occured: /usr/lib/lua/luci/template.lua:55: Failed to execute template 'cbi/tblsection'.
A runtime error occured: /usr/lib/lua/luci/template.lua:55: Failed to execute template 'cbi/dvalue'.
A runtime error occured: /usr/lib/lua/luci/model/uci.lua:143: attempt to call method 'get_all' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:407: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:99: in function

**Comment by kuoruan** [comment]
前两天就修复了，一直没来得及编译，刚刚编译好。

**Comment by kuoruan** [comment]
#32
