### ISSUE TITLE
lede识别不了客户端文件

### ISSUE THREAD

**Issue by Sounnuons** [kuoruan/luci-app-kcptun#34]
WNDR3800，MIPS ，下载kcptun客户端文件后用winscp上传到/root，权限0755，识别不了客户端文件，一直显示客户端文件配置有误，大佬，这种情况怎么整？

**Comment by kuoruan** [comment]
你用 ssh 进去运行一下看看能不能运行

**Comment by Sounnuons** [comment]
执行./client 输出illegal instrauction

**Comment by Sounnuons** [comment]
执行./client 输出 illegal instruction

**Comment by kuoruan** [comment]
什么版本？编译 OpenWrt/LEDE 时打开 ```MIPS FPU Emulator```

**Comment by Sounnuons** [comment]
从openwrt.org下载的已经编译的stable版本

**Comment by kuoruan** [comment]
Kcptun 版本？
官方版的 OpenWrt 是默认没编译 ```MIPS FPU Emulator``` 的

**Comment by Sounnuons** [comment]
kcptun用的1.4.4，client文件用的最新3月的，意思是我这固件有问题，开了MIPS FPU Emulator的固件就能运行了对吗？

**Comment by kuoruan** [comment]
对的

**Comment by Sounnuons** [comment]
OK，多谢大佬
