### ISSUE TITLE
MIPS FPU Emulator

### ISSUE THREAD

**Issue by Sounnuons** [kuoruan/luci-app-kcptun#35]
大大我是个小白，上次我问你关于标题的问题，我倒腾了几天，装了ubuntu，编译了新固件，kcptun是能用了，可是ss-libev又用不了了，是不是只有等适配了

**Comment by kuoruan** [comment]
kcptun 是不会影响 ss-libev 的，你所指的不能使用具体提现在哪里？

**Comment by Sounnuons** [comment]
最新版的sslibev装上后不能用，显示运行中，但是流量根本不走ss过

**Comment by kuoruan** [comment]
应该是 iptables 规则没对
