### ISSUE TITLE
更新到18.06分支就无法运行了

### ISSUE THREAD

**Issue by fuqiang03** [kuoruan/luci-app-kcptun#36]
更新到18.06分支就无法运行了

**Comment by kuoruan** [comment]
有什么报错信息吗？

**Comment by fuqiang03** [comment]
额 图片上不去了
日志里面没有任何的信息提示（包括插件的日志） 
这次18.06更新了luc-base 与主库的一样了 配置文件的读取方式貌似和以前不一样了
就是kcptun不执行了

**Comment by fuqiang03** [comment]
op这次更新真的跪了 颠倒执行 要不就是不执行 也不知道配置文件的参数是怎么传递的

**Comment by kuoruan** [comment]
得等两天我看看

**Comment by kuoruan** [comment]
我这里运行正常啊，用 master 源码编译的

你看看你的 ```/var/etc/kcptun/client.general.json``` 文件内容

**Comment by fuqiang03** [comment]
没有发现你说的文件 我用的是18.06

**Comment by kuoruan** [comment]
18.06 也测试通过了
你日志输出的什么？

**Comment by fuqiang03** [comment]
无日志数据

**Comment by kuoruan** [comment]
控制台运行 ```/etc/init.d/kcptun start```

**Comment by fuqiang03** [comment]
系统日志没有错误  插件日志没有启动

**Comment by fuqiang03** [comment]
这回运行了

**Comment by fuqiang03** [comment]
必须需要手动一次才能运行,之后就可以正常的使用了

**Comment by kuoruan** [comment]
重装一下

**Comment by fuqiang03** [comment]
我的事编译进去的 先删除包 在固件中安装？

**Comment by fuqiang03** [comment]
![Uploading QQ截图20180728234357.pn

g…]()

我从新下载了源码 没有任何的修改 依然无法启动kcptun 源码版本18.06-rc2 里面只有kcptun一个插件
单独安装ipk 则没有任何问题 但是编译到固件中就不行了

**Comment by kuoruan** [comment]
进启动项里边看看 kcptun 启用没有

**Comment by fuqiang03** [comment]
Initscripts里面 是禁止的  已经手动打开了  依然无法执行

**Comment by fuqiang03** [comment]
但是可以在Initscripts里面 点开始按钮  kcptun就能运行了  不点一次  lua页面是无法启动的

**Comment by kuoruan** [comment]
你这种是由于编译的时候没有执行到
```root/etc/uci-defaults/40_luci-kcptun``` 文件
我这里无法重现

**Comment by fuqiang03** [comment]
但是在/rom/etc/ uci-defaults  下面这个文件是存在的

**Comment by kuoruan** [comment]
是不是这个文件没有执行权限？

**Comment by fuqiang03** [comment]
775

**Comment by fuqiang03** [comment]
我重置固件 手动执行下看看

**Comment by fuqiang03** [comment]
没有效果

**Comment by fuqiang03** [comment]
我发现配置文件的权限变成了600 即使手动修改 保存配置后 就变成了600

**Comment by kuoruan** [comment]
这个文件会在编译时就执行，你看看你编译目录下的这个文件是不是没有执行权限

**Comment by fuqiang03** [comment]
权限都是775

**Comment by fuqiang03** [comment]
别的文件权限664的都能正常执行 总是感觉 官网的源码对配置文件的 执行方式有变化了

**Comment by kuoruan** [comment]
https://github.com/kuoruan/luci-app-kcptun/blob/master/Makefile#L25
你试试把这个函数去掉

**Comment by fuqiang03** [comment]
好的
有的插件能开启 但是不能关闭 我自己写的shell 颠倒执行 关闭了  却显示执行了

**Comment by kuoruan** [comment]
理论上说
https://github.com/openwrt/luci/blob/master/luci.mk#L192
这个函数都会执行到

**Comment by fuqiang03** [comment]
编译的时候makefile里面的东西 都会被执行 奇怪的是配置文件都能正常的被修改 但是到了调用init.d下面的文件的时候 好像什么也没发生似的

**Comment by fuqiang03** [comment]
没有效果

**Comment by fuqiang03** [comment]
![qq 20180804171854](https://user-images.githubusercontent.com/26851715/43676272-92441db4-9820-11e8-925f-85a4bce64ece.png)
/etc/init.d/kcptun stop后 就会出现上面的显现
手动shell后 已重启就会失效

**Comment by fuqiang03** [comment]
![qq 20181229182613](https://user-images.githubusercontent.com/26851715/50537149-54ab7200-0b97-11e9-9329-f39574363def.png)
发现个问题 路由器重启后貌似没有上图那样对kcptun 配置文件产生反应，18.06版本

**Comment by kuoruan** [comment]
看一下启动项里边有kcptun吗

**Comment by fuqiang03** [comment]
有的
![qq 20181229191518](https://user-images.githubusercontent.com/26851715/50537697-372dd680-0b9e-11e9-8b49-c47b499caa7d.png)

**Comment by kuoruan** [comment]
被禁用了

**Comment by fuqiang03** [comment]
额  他自己禁用的哦
