### ISSUE TITLE
客户端参数没法设置了

### ISSUE THREAD

**Issue by 3xpert** [kuoruan/luci-app-kcptun#37]
![chrome_2018-09-25_14-02-35](https://user-images.githubusercontent.com/8335065/45995937-d8ebe600-c0cc-11e8-81c9-7f2f9d84a604.png)

**Comment by kuoruan** [comment]
你是不是把配置文件给删了？
新建一个文件 /etc/config/kcptun

https://github.com/kuoruan/luci-app-kcptun/blob/master/root/etc/config/kcptun

**Comment by 3xpert** [comment]
这个文件在的啊，没有删

**Comment by kuoruan** [comment]
那你就卸载插件重装一下

**Comment by 3xpert** [comment]
这个动作已经重复两次了，问题依旧

**Comment by kuoruan** [comment]
打开 /etc/config/kcptun 看看里边的内容，有没有
```
config general 'general'
```

**Comment by 3xpert** [comment]
![image](https://user-images.githubusercontent.com/8335065/46000026-012e1180-c0da-11e8-9574-8b865777982a.png)

**Comment by kuoruan** [comment]
补全名称即可。

**Comment by 3xpert** [comment]
哦，试试

**Comment by 3xpert** [comment]
可以了，谢谢！
