### ISSUE TITLE
wndr3800的openwrt可以安装kcptun吗？有没有ipk包可以下载或是安装文件，谢谢啦

### ISSUE THREAD

**Issue by lunaticrz** [kuoruan/luci-app-kcptun#4]

**Comment by kuoruan** [comment]
你需要到网上找你路由器cpu对应的二进制文件

**Comment by lunaticrz** [comment]
呵呵，有找到二进制文件，就是不会安装了，有相关文档吗？谢谢啦。

2016-10-14 14:37 GMT+08:00 Hsing-Wang Liao notifications@github.com:

**Comment by kuoruan** [comment]
传到路由器上，在配置页配置好路径即可。

**Comment by lunaticrz** [comment]
在Kcptun - Settings 里的Client Exec File  /usr/bin/kcptun/client/，二进制文件是放在/usr/bin/kcptun/client/，提示 Not a Kcptun executable file.，是要在openwrt里面配置路径吗，在哪配置呢

**Comment by kuoruan** [comment]
@lunaticrz 说明你找的那个文件不适用于你的路由器，重新找
