### ISSUE TITLE
kcptun(1.4.5-1)日志目录不存在导致开机启动失败

### ISSUE THREAD

**Issue by wanghaokk** [kuoruan/luci-app-kcptun#43]
本人是openwrt新手
环境：VirtualBox运行的openwrt+LEDE
软件版本：
1.4.5-1 luci-app-kcptun

开机启动失败的System Log:

Sat Feb  9 18:34:51 2019 user.notice : kcptun.general.server=default validates as uciname with true
Sat Feb  9 18:34:51 2019 user.notice : kcptun.general.client_file=/usr/bin/kcptun-client validates as string with true
Sat Feb  9 18:34:51 2019 user.notice : kcptun.general.daemon_user=root validates as string with true
Sat Feb  9 18:34:51 2019 user.notice : kcptun.general.enable_logging=1 validates as bool with true
Sat Feb  9 18:34:51 2019 user.notice : kcptun.general.log_folder=/var/log/kcptun validates as directory with false

目前我是这样解决：
手工创建目录(mkdir -p /var/log/kcptun)，再执行/etc/init.d/kcptun start成功
或者手工在LEDE管理页面上，点击一下Save & Apply，也可以启动成功，进程变为Running

我的问题是：
kcptun启动脚本如何才能编辑呢？
或者怎样才能使/var/log/kcptun目录一直存在
我的openwrt每次重启之后，上次mkdir创建的目录都消失了，导致自动启动失败。。

**Comment by kuoruan** [comment]
```
https://github.com/kuoruan/luci-app-kcptun/blob/master/root/etc/init.d/kcptun#L207
```

日志文件夹会自己创建的，不清楚你那个是什么情况

**Comment by kuoruan** [comment]
你可以尝试修改日志目录为 /var/log 再启动试试
