### ISSUE TITLE
"--streambuf" 参数如何设置

### ISSUE THREAD

**Issue by pigpigabc123** [kuoruan/luci-app-kcptun#48]
smuxver参数 在+
https://github.com/kuoruan/luci-app-kcptun/commit/91f6516cdb2465a48c0263d0a46d88d3ce49b115

中已添加，实际使用kcp变得不稳定，是否与未设置"--streambuf" 参数有关系

**Comment by kuoruan** [comment]
版本还没发，待我发个版

**Comment by kuoruan** [comment]
v1.5.2-1
