### ISSUE TITLE
请问能编译个mt7620的kcptun吗？

### ISSUE THREAD

**Issue by Biercenter** [kuoruan/luci-app-kcptun#5]
有luci，苦于没有kcptun啊，自己编译kcptun到net/ipv4这步出错，跟wiki里的不一样，解决不了。

**Comment by shutup** [comment]
@Biercenter 我这里有一个20160906版的，https://github.com/shutup/kcptun_mip32le

**Comment by Biercenter** [comment]
谢谢分享！我现在用的是922版了，打算弄一个10月版的

**Comment by kuoruan** [comment]
官方已有
