### ISSUE TITLE
在openwrt 19.07 rc2上报错

### ISSUE THREAD

**Issue by adolink** [kuoruan/luci-app-kcptun#50]
500 内部服务器错误

对不起，服务器遇到未知错误。

Failed to execute cbi dispatcher target for entry '/admin/services/kcptun/settings'.
The called action terminated with an exception:
/usr/lib/lua/luci/template.lua:97: Failed to execute template 'cbi/map'.
A runtime error occurred: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'kcptun/status'.
A runtime error occurred: /usr/lib/lua/luci/model/kcptun.lua:49: module 'luci.model.ipkg' not found:
	no field package.preload['luci.model.ipkg']
	no file './luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg.lua'
	no file '/usr/share/lua/luci/model/ipkg/init.lua'
	no file '/usr/lib/lua/luci/model/ipkg.lua'
	no file '/usr/lib/lua/luci/model/ipkg/init.lua'
	no file './luci/model/ipkg.so'
	no file '/usr/lib/lua/luci/model/ipkg.so'
	no file '/usr/lib/lua/loadall.so'
	no file './luci.so'
	no file '/usr/lib/lua/luci.so'
	no file '/usr/lib/lua/loadall.so'
stack traceback:
	[C]: in function 'require'
	/usr/lib/lua/luci/model/kcptun.lua:49: in function 'get_luci_version'
	[string "/usr/lib/lua/luci/view/kcptun/status.htm"]:7: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function 
	(tail call): ?
	/usr/lib/lua/luci/cbi.lua:282: in function 'render'
	/usr/lib/lua/luci/cbi.lua:266: in function 'render_children'
	[string "/usr/lib/lua/luci/view/cbi/map.htm"]:6: in main chunk
stack traceback:
	[C]: in function 'error'
	/usr/lib/lua/luci/template.lua:97: in function 
	(tail call): ?
	/usr/lib/lua/luci/cbi.lua:257: in function 'render'
	/usr/lib/lua/luci/cbi.lua:440: in function 'render'
	/usr/lib/lua/luci/dispatcher.lua:1025: in function 

luci-compat已经安装了luci-app-v2ray是可以使用的

**Comment by kuoruan** [comment]
安装 ```luci.model.ipkg```

**Comment by pigpigabc123** [comment]
> 安装 `luci.model.ipkg`

实测安装luci-lib-ipkg后恢复正常
