### ISSUE TITLE
R20.4.8 lede 跑不起来

### ISSUE THREAD

**Issue by keeno1982** [kuoruan/luci-app-kcptun#53]
![openwrt](https://user-images.githubusercontent.com/13664097/79448863-c6b9fb80-8014-11ea-8b3c-c864846fd859.png)

![luci-app-kcptun](https://user-images.githubusercontent.com/13664097/79448536-2a8ff480-8014-11ea-93d3-2029898fed8e.png)
客户端状态 未运行

日志文件的最新 50 行：

无日志数据。

系统日志的最新 50 行：

Thu Apr 16 17:21:44 2020 daemon.info procd: Instance kcptun::instance1 s in a crash loop 7 crashes, 0 seconds since last crash
Thu Apr 16 17:21:43 2020 daemon.info kcptun: Starting kcptun with 248786000 virt mem
Thu Apr 16 17:07:04 2020 daemon.info procd: Instance kcptun::instance1 s in a crash loop 6 crashes, 0 seconds since last crash
Thu Apr 16 16:27:06 2020 daemon.info kcptun: Starting kcptun with 248786000 virt mem

在控制台直接命令调用usr/bin目录下的kcptun-client执行文件是可以跑的

**Comment by kuoruan** [comment]
内存不足了，把内存限制放开

**Comment by keeno1982** [comment]
@kuoruan 怎么放开？我没做限制啊。NEO2这机子内存是512M，应该是够用的，除了SSR我没开其它的。同样的kcptun配置，直接跑命令是没问题的，就是Luci跑不了。

**Comment by kuoruan** [comment]
```vi /root/etc/config/kcptun```

mem_percentage 改为 90 或 98

**Comment by sqliuchang** [comment]
@kuoruan 为啥最新的commit要限制内存，kcptun在这方面有缺陷吗？

**Comment by sqliuchang** [comment]
> NEO2这机子内存是512M

可以考虑开启zram，还是比较好用的，我看chrome os默认设置zram为物理内存的1.5倍

**Comment by keeno1982** [comment]
mem_percentage改成98了，还是这个错
Sat Apr 18 20:48:31 2020 daemon.info procd: Instance kcptun::instance1 s in a crash loop 6 crashes, 0 seconds since last crash
Sat Apr 18 20:47:47 2020 daemon.info kcptun: Starting kcptun with 487620560 virt mem

**Comment by kuoruan** [comment]
改为 0

**Comment by keeno1982** [comment]
@kuoruan 老大，改成0也不行
Mon Apr 20 10:47:27 2020 daemon.err kcptun: Config validate failed.

**Comment by kuoruan** [comment]
用新版吧

**Comment by keeno1982** [comment]
牛，新版的可以跑了！
