### ISSUE TITLE
LEDE版出现500 Internal Server Error

### ISSUE THREAD

**Issue by liyiecho** [kuoruan/luci-app-kcptun#7]
500 Internal Server Error
Sorry, the server encountered an unexpected error.
```

/usr/lib/lua/luci/dispatcher.lua:460: Failed to execute function dispatcher target for entry '/admin/services/kcptun'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:460: Failed to execute cbi dispatcher target for entry '/admin/services/kcptun/overview'.
The called action terminated with an exception:
/usr/lib/lua/luci/template.lua:97: Failed to execute template 'cbi/simpleform'.
A runtime error occured: /usr/lib/lua/luci/template.lua:97: Failed to execute template 'kcptun/overview'.
A runtime error occured: [string "/usr/lib/lua/luci/view/kcptun/overview.htm"]:32: attempt to index field 'luci-app-kcptun' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:460: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:141: in function 
```

重启/etc/init.d/kcptun后，luci恢复正常
而且有时候会变成不工作状态，需要手动重启服务

**Comment by kuoruan** [comment]
关于第一个问题，希望能给个配置的界面截图
第二个问题，在不工作的时候是否是 CPU 或者内存占用过高？我过两天会更新一个监控进程的功能

**Comment by liyiecho** [comment]
重启后又正常了
<img width="772" alt="screen shot 2016-11-28 at 17 48 57" src="https://cloud.githubusercontent.com/assets/5213722/20663755/99f6a80e-b593-11e6-9554-21136f817570.png">

这是kcptun的配置
![6de11116-49e9-40af-bafa-28cbcd708906](https://cloud.githubusercontent.com/assets/5213722/20663786/b23f4772-b593-11e6-818e-3d56cfb62e65.png)

**Comment by kuoruan** [comment]
不是，我要的是 设置 那个TAB的截图，然后是 /etc/config/kcptun 的内容

**Comment by liyiecho** [comment]
设置
![4ee3ce48-423a-4d8a-8182-050c834671a0](https://cloud.githubusercontent.com/assets/5213722/20664498/792691b8-b596-11e6-81dd-f93b55c2653e.png)

配置
![174b5066-f5ba-4c19-93a1-8dacc6390566](https://cloud.githubusercontent.com/assets/5213722/20664557/ac86baa6-b596-11e6-8c99-010bbff268e5.png)

**Comment by kuoruan** [comment]
/usr/lib/lua/luci/view/kcptun/overview.htm 这个文件的第32行是什么？

**Comment by liyiecho** [comment]
红色标记的为第32行的内容
![53efa8a7-66e2-4548-86a1-6f5f8b0d94f8](https://cloud.githubusercontent.com/assets/5213722/20666044/2fdd82ee-b59d-11e6-8201-d4be5b9738f8.png)

**Comment by kuoruan** [comment]
这里我看了，没什么问题。现在暂时不知道问题出在哪里，待测

**Comment by haruhitamako** [comment]
这是因为你没把客户端文件的路径指向到文件，luci读取不到客户端文件的版本。你需要在路径中把客户端文件的名字也带上
