### ISSUE TITLE
"Server IP"只能是ip地址吗？

### ISSUE THREAD

**Issue by prowong** [kuoruan/luci-app-kcptun#9]
client设置中的Server IP，用域名也是可以的吧，我用json配置使用域名正常使用。

**Comment by kuoruan** [comment]
我搞不明白，既然域名都能直接解析到IP为什么不直接填 IP？

**Comment by prowong** [comment]
可是，ip不是固定的呀，虽然vps不重启ip就不会改变，但是域名方便易记啊。而且，正如博客所说，kcptun跟s-s没有半毛钱关系，去掉限制为ip地址可以用在更多场景。
可以了，把client.lua的server_ip的o.datatype = "ipaddr"去掉就可以了。

**Comment by kuoruan** [comment]
已实现
